export enum TESTNET_BLOCKCHAIN_NAME {
    KOVAN = 'KOVAN',
    BINANCE_SMART_CHAIN_TESTNET = 'BSC_TESTNET',
    POLYGON_TESTNET = 'POLYGON_TESTNET',
    HARMONY_TESTNET = 'HARMONY_TESTNET',
    AVALANCHE_TESTNET = 'AVALANCHE_TESTNET',
    MOONRIVER_TESTNET = 'MOONRIVER_TESTNET',
    FANTOM_TESTNET = 'FANTOM_TESTNET'
}

export enum MAINNET_BLOCKCHAIN_NAME {
    ETHEREUM = 'ETH',
    BINANCE_SMART_CHAIN = 'BSC',
    POLYGON = 'POLYGON',
    AVALANCHE = 'AVALANCHE',
    MOONRIVER = 'MOONRIVER',
    FANTOM = 'FANTOM',
    HARMONY = 'HARMONY',
    ARBITRUM = 'ARBITRUM',
    AURORA = 'AURORA',
    TELOS = 'TELOS'
}

export const BLOCKCHAIN_NAME = {
    ...MAINNET_BLOCKCHAIN_NAME,
    ...TESTNET_BLOCKCHAIN_NAME
};

// eslint-disable-next-line @typescript-eslint/no-redeclare
export type BlockchainName = MAINNET_BLOCKCHAIN_NAME | TESTNET_BLOCKCHAIN_NAME;
