export enum BLOCKCHAIN_NAME {
    ETHEREUM = 'ETH',
    BINANCE_SMART_CHAIN = 'BSC',
    POLYGON = 'POLYGON',
    AVALANCHE = 'AVALANCHE',
    MOONRIVER = 'MOONRIVER',
    HARMONY = 'HARMONY',
    FANTOM = 'FANTOM',
    // testnets
    KOVAN = 'KOVAN',
    BINANCE_SMART_CHAIN_TESTNET = 'BSC_TESTNET',
    POLYGON_TESTNET = 'POLYGON_TESTNET',
    HARMONY_TESTNET = 'HARMONY_TESTNET',
    AVALANCHE_TESTNET = 'AVALANCHE_TESTNET',
    MOONRIVER_TESTNET = 'MOONRIVER_TESTNET',
    FANTOM_TESTNET = 'FANTOM_TESTNET'
}
