export enum EXACT_INPUT_REGULAR_SWAP_METHOD {
    TOKENS_TO_TOKENS = 'swapExactTokensForTokens',
    ETH_TO_TOKENS = 'swapExactETHForTokens',
    TOKENS_TO_ETH = 'swapExactTokensForETH'
}

export enum EXACT_OUTPUT_REGULAR_SWAP_METHOD {
    TOKENS_TO_TOKENS = 'swapTokensForExactTokens',
    ETH_TO_TOKENS = 'swapETHForExactTokens',
    TOKENS_TO_ETH = 'swapTokensForExactETH'
}

export enum EXACT_INPUT_SUPPORTING_FEE_SWAP_METHOD {
    TOKENS_TO_TOKENS_SUPPORTING_FEE = 'swapExactTokensForTokensSupportingFeeOnTransferTokens',
    ETH_TO_TOKENS_SUPPORTING_FEE = 'swapExactETHForTokensSupportingFeeOnTransferTokens',
    TOKENS_TO_ETH_SUPPORTING_FEE = 'swapExactTokensForETHSupportingFeeOnTransferTokens'
}

export enum EXACT_OUTPUT_SUPPORTING_FEE_SWAP_METHOD {
    TOKENS_TO_TOKENS_SUPPORTING_FEE = 'swapTokensForExactTokensSupportingFeeOnTransferTokens',
    ETH_TO_TOKENS_SUPPORTING_FEE = 'swapETHForExactTokensSupportingFeeOnTransferTokens',
    TOKENS_TO_ETH_SUPPORTING_FEE = 'swapTokensForExactETHSupportingFeeOnTransferTokens'
}

export const REGULAR_SWAP_METHOD = {
    input: EXACT_INPUT_REGULAR_SWAP_METHOD,
    output: EXACT_OUTPUT_REGULAR_SWAP_METHOD
};

export const SUPPORTING_FEE_SWAP_METHOD = {
    input: EXACT_INPUT_SUPPORTING_FEE_SWAP_METHOD,
    output: EXACT_OUTPUT_SUPPORTING_FEE_SWAP_METHOD
};

export const SupportingFeeMethodsMapping = {
    [EXACT_INPUT_REGULAR_SWAP_METHOD.TOKENS_TO_TOKENS]:
        EXACT_INPUT_SUPPORTING_FEE_SWAP_METHOD.TOKENS_TO_TOKENS_SUPPORTING_FEE,
    [EXACT_INPUT_REGULAR_SWAP_METHOD.ETH_TO_TOKENS]:
        EXACT_INPUT_SUPPORTING_FEE_SWAP_METHOD.ETH_TO_TOKENS_SUPPORTING_FEE,
    [EXACT_INPUT_REGULAR_SWAP_METHOD.TOKENS_TO_ETH]:
        EXACT_INPUT_SUPPORTING_FEE_SWAP_METHOD.TOKENS_TO_ETH_SUPPORTING_FEE,
    [EXACT_OUTPUT_REGULAR_SWAP_METHOD.TOKENS_TO_TOKENS]:
        EXACT_OUTPUT_SUPPORTING_FEE_SWAP_METHOD.TOKENS_TO_TOKENS_SUPPORTING_FEE,
    [EXACT_OUTPUT_REGULAR_SWAP_METHOD.ETH_TO_TOKENS]:
        EXACT_OUTPUT_SUPPORTING_FEE_SWAP_METHOD.ETH_TO_TOKENS_SUPPORTING_FEE,
    [EXACT_OUTPUT_REGULAR_SWAP_METHOD.TOKENS_TO_ETH]:
        EXACT_OUTPUT_SUPPORTING_FEE_SWAP_METHOD.TOKENS_TO_ETH_SUPPORTING_FEE
};

export type RegularSwapMethod = EXACT_INPUT_REGULAR_SWAP_METHOD | EXACT_OUTPUT_REGULAR_SWAP_METHOD;
export type SupportingFeeSwapMethod =
    | EXACT_OUTPUT_SUPPORTING_FEE_SWAP_METHOD
    | EXACT_INPUT_SUPPORTING_FEE_SWAP_METHOD;
