export enum CelerTransferStatus {
    XS_UNKNOWN,
    XS_WAITING_FOR_SGN_CONFIRMATION,
    XS_WAITING_FOR_FUND_RELEASE,
    XS_COMPLETED,
    XS_TO_BE_REFUND,
    XS_REFUND_TO_BE_CONFIRMED,
    XS_REFUNDED
}
