export enum CelerTransferStatus {
    TRANSFER_UNKNOWN,
    TRANSFER_SUBMITTING,
    TRANSFER_FAILED,
    TRANSFER_WAITING_FOR_SGN_CONFIRMATION,
    TRANSFER_WAITING_FOR_FUND_RELEASE,
    TRANSFER_COMPLETED,
    TRANSFER_TO_BE_REFUNDED,
    TRANSFER_REQUESTING_REFUND,
    TRANSFER_REFUND_TO_BE_CONFIRMED,
    TRANSFER_CONFIRMING_YOUR_REFUND,
    TRANSFER_REFUNDED
}
