import { BLOCKCHAIN_NAME } from 'src/core/blockchain/models/blockchain-name';

export const viaCrossChainSupportedBlockchains = [
    BLOCKCHAIN_NAME.ETHEREUM,
    BLOCKCHAIN_NAME.POLYGON,
    BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN,
    BLOCKCHAIN_NAME.OPTIMISM,
    BLOCKCHAIN_NAME.ARBITRUM,
    BLOCKCHAIN_NAME.FANTOM,
    BLOCKCHAIN_NAME.AVALANCHE,
    BLOCKCHAIN_NAME.HARMONY,
    BLOCKCHAIN_NAME.GNOSIS,
    BLOCKCHAIN_NAME.FUSE,
    BLOCKCHAIN_NAME.MOONBEAM,
    BLOCKCHAIN_NAME.MOONRIVER,
    BLOCKCHAIN_NAME.AURORA,
    BLOCKCHAIN_NAME.CRONOS,
    BLOCKCHAIN_NAME.CELO,
    BLOCKCHAIN_NAME.BOBA
] as const;

export type ViaCrossChainSupportedBlockchain = (typeof viaCrossChainSupportedBlockchains)[number];
