/**
 * List of instant trade types.
 */
export const TRADE_TYPE = {
    // Ethereum
    ONE_INCH_ETHEREUM: 'ONE_INCH_ETHEREUM',
    SUSHI_SWAP_ETHEREUM: 'SUSHI_SWAP_ETHEREUM',
    UNISWAP_V2: 'UNISWAP_V2',
    UNI_SWAP_V3_ETHEREUM: 'UNI_SWAP_V3_ETHEREUM',
    ZRX_ETHEREUM: 'ZRX_ETHEREUM',

    // Bsc
    ONE_INCH_BSC: 'ONE_INCH_BSC',
    PANCAKE_SWAP: 'PANCAKE_SWAP',
    SUSHI_SWAP_BSC: 'SUSHI_SWAP_BSC',

    // Polygon
    ALGEBRA: 'ALGEBRA',
    ONE_INCH_POLYGON: 'ONE_INCH_POLYGON',
    QUICK_SWAP: 'QUICK_SWAP',
    SUSHI_SWAP_POLYGON: 'SUSHI_SWAP_POLYGON',
    UNI_SWAP_V3_POLYGON: 'UNI_SWAP_V3_POLYGON',

    // Avalanche
    JOE: 'JOE',
    ONE_INCH_AVALANCHE: 'ONE_INCH_AVALANCHE',
    PANGOLIN: 'PANGOLIN',
    SUSHI_SWAP_AVALANCHE: 'SUSHI_SWAP_AVALANCHE',

    // Moonriver
    SOLAR_BEAM: 'SOLAR_BEAM',
    SUSHI_SWAP_MOONRIVER: 'SUSHI_SWAP_MOONRIVER',

    // Fantom
    SPIRIT_SWAP: 'SPIRIT_SWAP',
    SPOOKY_SWAP: 'SPOOKY_SWAP',
    SUSHI_SWAP_FANTOM: 'SUSHI_SWAP_FANTOM',
    ONE_INCH_FANTOM: 'ONE_INCH_FANTOM',

    // Harmony
    SUSHI_SWAP_HARMONY: 'SUSHI_SWAP_HARMONY',
    VIPER_SWAP: 'VIPER_SWAP',

    // Arbitrum
    ONE_INCH_ARBITRUM: 'ONE_INCH_ARBITRUM',
    SUSHI_SWAP_ARBITRUM: 'SUSHI_SWAP_ARBITRUM',
    UNI_SWAP_V3_ARBITRUM: 'UNI_SWAP_V3_ARBITRUM',

    // Aurora
    TRISOLARIS: 'TRISOLARIS',
    WANNA_SWAP: 'WANNA_SWAP',

    // Telos
    SUSHI_SWAP_TELOS: 'SUSHI_SWAP_TELOS',
    ZAPPY: 'ZAPPY'
} as const;

/**
 * Instant trade type.
 */
export type TradeType = keyof typeof TRADE_TYPE;
