export const ONEINCH_TRADE_TYPE = {
    ONE_INCH_ETHEREUM: 'ONE_INCH_ETHEREUM',
    ONE_INCH_BSC: 'ONE_INCH_BSC',
    ONE_INCH_POLYGON: 'ONE_INCH_POLYGON',
    ONE_INCH_ARBITRUM: 'ONE_INCH_ARBITRUM',
    ONE_INCH_FANTOM: 'ONE_INCH_FANTOM',
    ONE_INCH_AVALANCHE: 'ONE_INCH_AVALANCHE'
} as const;

export const SUSHI_SWAP_TRADE_TYPE = {
    SUSHI_SWAP_ETHEREUM: 'SUSHI_SWAP_ETHEREUM',
    SUSHI_SWAP_BSC: 'SUSHI_SWAP_BSC',
    SUSHI_SWAP_POLYGON: 'SUSHI_SWAP_POLYGON',
    SUSHI_SWAP_AVALANCHE: 'SUSHI_SWAP_AVALANCHE',
    SUSHI_SWAP_FANTOM: 'SUSHI_SWAP_FANTOM',
    SUSHI_SWAP_HARMONY: 'SUSHI_SWAP_HARMONY',
    SUSHI_SWAP_MOONRIVER: 'SUSHI_SWAP_MOONRIVER',
    SUSHI_SWAP_ARBITRUM: 'SUSHI_SWAP_ARBITRUM',
    SUSHI_SWAP_TELOS: 'SUSHI_SWAP_TELOS'
} as const;

export const UNI_SWAP_V3_TRADE_TYPE = {
    UNI_SWAP_V3_ETHEREUM: 'UNI_SWAP_V3_ETHEREUM',
    UNI_SWAP_V3_POLYGON: 'UNI_SWAP_V3_POLYGON',
    UNI_SWAP_V3_ARBITRUM: 'UNI_SWAP_V3_ARBITRUM'
} as const;

export const UNI_SWAP_V2_TRADE_TYPE = {
    UNISWAP_V2: 'UNISWAP_V2',
    PANCAKE_SWAP: 'PANCAKE_SWAP',
    QUICK_SWAP: 'QUICK_SWAP',
    JOE: 'JOE',
    PANGOLIN: 'PANGOLIN',
    SPIRIT_SWAP: 'SPIRIT_SWAP',
    SPOOKY_SWAP: 'SPOOKY_SWAP',
    SOLAR_BEAM: 'SOLAR_BEAM',
    VIPER_SWAP: 'VIPER_SWAP',
    TRISOLARIS: 'TRISOLARIS',
    WANNA_SWAP: 'WANNA_SWAP',
    ZAPPY: 'ZAPPY'
} as const;

export const TRADE_TYPE = {
    ZRX_ETHEREUM: 'ZRX_ETHEREUM',
    ALGEBRA: 'ALGEBRA',
    WRAPPED: 'WRAPPED',
    RAYDIUM: 'RAYDIUM',
    REF_FINANCE: 'REF_FINANCE',
    ...UNI_SWAP_V2_TRADE_TYPE,
    ...UNI_SWAP_V3_TRADE_TYPE,
    ...SUSHI_SWAP_TRADE_TYPE,
    ...ONEINCH_TRADE_TYPE
} as const;

export type TradeType = keyof typeof TRADE_TYPE;
