import { TRADE_TYPE, TradeType } from 'src/features/instant-trades/models/trade-type';

export const rangoProviders: Record<string, TradeType> = {
    SpookySwap: TRADE_TYPE.SPOOKY_SWAP,
    OneInchArbitrum: TRADE_TYPE.ONE_INCH,
    OneInchBsc: TRADE_TYPE.ONE_INCH,
    OneInchEth: TRADE_TYPE.ONE_INCH,
    OneInchGnosis: TRADE_TYPE.ONE_INCH,
    OneInchOptimism: TRADE_TYPE.ONE_INCH,
    OneInchPolygon: TRADE_TYPE.ONE_INCH,
    TrisolarisSwap: TRADE_TYPE.TRISOLARIS,
    AuroraSwap: TRADE_TYPE.AURORA_SWAP,
    BeamSwap: TRADE_TYPE.BEAM_SWAP,
    CronaSwap: TRADE_TYPE.CRONA_SWAP,
    MMFinance: TRADE_TYPE.MM_FINANCE,
    VVSFinance: TRADE_TYPE.VVS_FINANCE,
    Jupiter: TRADE_TYPE.JUPITER,
    OpenOceanFantom: TRADE_TYPE.OPEN_OCEAN,
    PancakeSwapBsc: TRADE_TYPE.PANCAKE_SWAP,
    PangolinSwap: TRADE_TYPE.PANGOLIN,
    'ParaSwap Avalanche': TRADE_TYPE.PARA_SWAP,
    'ParaSwap Polygon': TRADE_TYPE.PARA_SWAP,
    QuickSwap: TRADE_TYPE.QUICK_SWAP,
    SolarbeamSwap: TRADE_TYPE.SOLAR_BEAM,
    StellaSwap: TRADE_TYPE.STELLA_SWAP,
    SushiArbitrum: TRADE_TYPE.SUSHI_SWAP,
    EthUniSwapv2: TRADE_TYPE.UNISWAP_V2,
    ViperSwap: TRADE_TYPE.VIPER_SWAP,
    VoltageSwap: TRADE_TYPE.VOLTAGE_SWAP
};
