export enum TxStatus {
    PENDING = 'PENDING',
    SUCCESS = 'SUCCESS',
    FAIL = 'FAIL',
    FALLBACK = 'FALLBACK',
    REVERT = 'REVERT',
    UNKNOWN = 'UNKNOWN',
    READY_TO_CLAIM = 'READY_TO_CLAIM'
}
